version: '3.2'
services:
  cypress:
    image: "cypress/included:6.4.0"
    environment:
      - CYPRESS_baseUrl=https://amazon.com.br
      - shm-size=1g
    working_dir: /e2e
    volumes:
      - ./:/e2e
